import WaltzParams

"""! Lookup dictionary for waltz parameters in the Chipzel soundtrack"""
CHIPZEL_SONG_PARAMS = dict({
    'boss_1':   WaltzParams.WaltzParams("../../data/music/boss_1_chp.ogg",   120, False, False, 10, "./music/boss_1_chp.ogg"  ),
    'boss_2':   WaltzParams.WaltzParams("../../data/music/boss_2_chp.ogg",   175, False, False, 10, "./music/boss_2_chp.ogg"  ),
    'boss_3':   WaltzParams.WaltzParams("../../data/music/boss_3_chp.ogg",   123, True,  False, 10, "./music/boss_3_chp.ogg"  ),
    'boss_4':   WaltzParams.WaltzParams("../../data/music/boss_4_chp.ogg",   126, False, True,  10, "./music/boss_4_chp.ogg"  ),
    'boss_5':   WaltzParams.WaltzParams("../../data/music/boss_5_chp.ogg",   140, False, False, 10, "./music/boss_5_chp.ogg"  ),
    'boss_6':   WaltzParams.WaltzParams("../../data/music/boss_6_chp.ogg",   140, False, False, 10, "./music/boss_6_chp.ogg"  ),
    'boss_6a':  WaltzParams.WaltzParams("../../data/music/boss_6_chpa.ogg",  160, False, False, 10, "./music/boss_6_chpa.ogg" ),
    'boss_7':   WaltzParams.WaltzParams("../../data/music/boss_7_chp.ogg",   0,   False, False, 10, "./music/boss_7_chp.ogg",  [], "../../data/music/boss_7.txt"),
    'boss_8':   WaltzParams.WaltzParams("../../data/music/boss_8_chp.ogg",   120, False, True,  10, "./music/boss_8_chp.ogg",  [48]),
    'boss_9':   WaltzParams.WaltzParams("../../data/music/boss_9_chp.ogg",   150, False, False, 10, "./music/boss_9_chp.ogg"  ),
    'lobby':    WaltzParams.WaltzParams("../../data/music/lobby_chp.ogg",    130, False, False, 10, "./music/lobby_chp.ogg"   ),
    'training': WaltzParams.WaltzParams("../../data/music/training_chp.ogg", 120, False, True,  10, "./music/training_chp.ogg"),
    'zone1_1':  WaltzParams.WaltzParams("../../data/music/zone1_1_chp.ogg",  115, False, False, 10, "./music/zone1_1_chp.ogg" ),
    'zone1_2':  WaltzParams.WaltzParams("../../data/music/zone1_2_chp.ogg",  130, True,  False, 10, "./music/zone1_2_chp.ogg" ),
    'zone1_3':  WaltzParams.WaltzParams("../../data/music/zone1_3_chp.ogg",  140, False, True,  10, "./music/zone1_3_chp.ogg" ),
    'zone2_1':  WaltzParams.WaltzParams("../../data/music/zone2_1_chp.ogg",  130, True,  True,  10, "./music/zone2_1_chp.ogg" ),
    'zone2_2':  WaltzParams.WaltzParams("../../data/music/zone2_2_chp.ogg",  140, False, False, 10, "./music/zone2_2_chp.ogg" ),
    'zone2_3':  WaltzParams.WaltzParams("../../data/music/zone2_3_chp.ogg",  150, False, True,  10, "./music/zone2_3_chp.ogg" ),
    'zone3_1c': WaltzParams.WaltzParams("../../data/music/zone3_1_chpc.ogg", 135, False, False, 10, "./music/zone3_1_chpc.ogg"),
    'zone3_1h': WaltzParams.WaltzParams("../../data/music/zone3_1_chph.ogg", 135, False, True,  10, "./music/zone3_1_chph.ogg"),
    'zone3_2c': WaltzParams.WaltzParams("../../data/music/zone3_2_chpc.ogg", 145, True,  False, 10, "./music/zone3_2_chpc.ogg"),
    'zone3_2h': WaltzParams.WaltzParams("../../data/music/zone3_2_chph.ogg", 145, True,  True,  10, "./music/zone3_2_chph.ogg"),
    'zone3_3c': WaltzParams.WaltzParams("../../data/music/zone3_3_chpc.ogg", 155, False, False, 10, "./music/zone3_3_chpc.ogg"),
    'zone3_3h': WaltzParams.WaltzParams("../../data/music/zone3_3_chph.ogg", 155, False, True,  10, "./music/zone3_3_chph.ogg"),
    'zone4_1':  WaltzParams.WaltzParams("../../data/music/zone4_1_chp.ogg",  130, False, False, 10, "./music/zone4_1_chp.ogg" ),
    'zone4_2':  WaltzParams.WaltzParams("../../data/music/zone4_2_chp.ogg",  145, False, False, 10, "./music/zone4_2_chp.ogg" ),
    'zone4_3':  WaltzParams.WaltzParams("../../data/music/zone4_3_chp.ogg",  160, False, True,  10, "./music/zone4_3_chp.ogg" ),
    'zone5_1':  WaltzParams.WaltzParams("../../data/music/zone5_1_chp.ogg",  130, False, False, 10, "./music/zone5_1_chp.ogg" ),
    'zone5_2':  WaltzParams.WaltzParams("../../data/music/zone5_2_chp.ogg",  140, True,  True,  10, "./music/zone5_2_chp.ogg" ),
    'zone5_3':  WaltzParams.WaltzParams("../../data/music/zone5_3_chp.ogg",  155, False, False, 10, "./music/zone5_3_chp.ogg", [112, 152, 336])
})
