"""! Provides a lookup dictionary for waltz parameters in the Danganronpa soundtrack"""
import WaltzParams

DANGANRONPA_SONG_PARAMS = dict({
    'boss_1':   WaltzParams.WaltzParams("../../data/music/boss_1_6.ogg",   120, False, False, 10,  "./music/boss_1_6.ogg"  ),
    'boss_2':   WaltzParams.WaltzParams("../../data/music/boss_2_6.ogg",   175, False, True,  10,  "./music/boss_2_6.ogg"  ),
    'boss_3':   WaltzParams.WaltzParams("../../data/music/boss_3_6.ogg",   123, False, False, 10,  "./music/boss_3_6.ogg"  ),
    'boss_4':   WaltzParams.WaltzParams("../../data/music/boss_4_6.ogg",   126, False, False, 10,  "./music/boss_4_6.ogg"  ),
    'boss_5':   WaltzParams.WaltzParams("../../data/music/boss_5_6.ogg",   140, False, False, 10,  "./music/boss_5_6.ogg"  ),
    'boss_6':   WaltzParams.WaltzParams("../../data/music/boss_6_6.ogg",   140, False, False, 10,  "./music/boss_6_6.ogg"  ),
    'boss_6a':  WaltzParams.WaltzParams("../../data/music/boss_6_6a.ogg",  160, False, False, 10,  "./music/boss_6_6a.ogg" ),
    'boss_7':   WaltzParams.WaltzParams("../../data/music/boss_7_6.ogg",   0,   False, False, -45, "./music/boss_7_6.ogg",  beatmapFile="../../data/music/boss_7.txt"),
    'boss_8':   WaltzParams.WaltzParams("../../data/music/boss_8_6.ogg",   120, False, True,  10,  "./music/boss_8_6.ogg",  timeSwitchBeats=[48]),
    'lobby':    WaltzParams.WaltzParams("../../data/music/lobby_6.ogg",    130, False, False, 10,  "./music/lobby_6.ogg"   ),
    'training': WaltzParams.WaltzParams("../../data/music/training_6.ogg", 120, False, True,  10,  "./music/training_6.ogg"),
    'zone1_1':  WaltzParams.WaltzParams("../../data/music/zone1_1_6.ogg",  115, False, True,  10,  "./music/zone1_1_6.ogg" ),
    'zone1_2':  WaltzParams.WaltzParams("../../data/music/zone1_2_6.ogg",  130, False, False, 10,  "./music/zone1_2_6.ogg" ),
    'zone1_3':  WaltzParams.WaltzParams("../../data/music/zone1_3_6.ogg",  140, False, False, 10,  "./music/zone1_3_6.ogg" ),
    'zone2_1':  WaltzParams.WaltzParams("../../data/music/zone2_1_6.ogg",  130, False, False, 10,  "./music/zone2_1_6.ogg" ),
    'zone2_2':  WaltzParams.WaltzParams("../../data/music/zone2_2_6.ogg",  140, False, True,  10,  "./music/zone2_2_6.ogg" ),
    'zone2_3':  WaltzParams.WaltzParams("../../data/music/zone2_3_6.ogg",  150, False, False, 10,  "./music/zone2_3_6.ogg" ),
    'zone3_1c': WaltzParams.WaltzParams("../../data/music/zone3_1_6c.ogg", 135, False, False, 10,  "./music/zone3_1_6c.ogg"),
    'zone3_1h': WaltzParams.WaltzParams("../../data/music/zone3_1_6h.ogg", 135, False, True,  10,  "./music/zone3_1_6h.ogg"),
    'zone3_2c': WaltzParams.WaltzParams("../../data/music/zone3_2_6c.ogg", 145, False, False, 10,  "./music/zone3_2_6c.ogg"),
    'zone3_2h': WaltzParams.WaltzParams("../../data/music/zone3_2_6h.ogg", 145, False, True,  10,  "./music/zone3_2_6h.ogg"),
    'zone3_3c': WaltzParams.WaltzParams("../../data/music/zone3_3_6c.ogg", 155, False, False, 10,  "./music/zone3_3_6c.ogg"),
    'zone3_3h': WaltzParams.WaltzParams("../../data/music/zone3_3_6h.ogg", 155, False, True,  10,  "./music/zone3_3_6h.ogg"),
    'zone4_1':  WaltzParams.WaltzParams("../../data/music/zone4_1_6.ogg",  130, False, False, 10,  "./music/zone4_1_6.ogg" ),
    'zone4_2':  WaltzParams.WaltzParams("../../data/music/zone4_2_6.ogg",  145, False, False, 10,  "./music/zone4_2_6.ogg" ),
    'zone4_3':  WaltzParams.WaltzParams("../../data/music/zone4_3_6.ogg",  160, False, True,  10,  "./music/zone4_3_6.ogg" ),
})
